// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {logger} from '../models';
import {config} from '../models';

export function CheckPort(arg1:number):Promise<boolean>;

export function DeleteConfig(arg1:string):Promise<void>;

export function GenerateSelfSignedCert():Promise<string>;

export function GetRecentLogs(arg1:number):Promise<Array<logger.Entry>>;

export function Init():Promise<void>;

export function ListConfigs():Promise<Array<config.TunnelConfig>>;

export function ParseHopChainString(arg1:string):Promise<Array<config.HopConfig>>;

export function SaveConfig(arg1:config.TunnelConfig):Promise<config.TunnelConfig>;

export function StartAll():Promise<void>;

export function StartTunnel(arg1:string):Promise<void>;

export function StopAll():Promise<void>;

export function StopTunnel(arg1:string):Promise<void>;

export function TestTunnelConfig(arg1:config.TunnelConfig):Promise<void>;
