// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPort(arg1) {
  return window['go']['main']['App']['CheckPort'](arg1);
}

export function DeleteConfig(arg1) {
  return window['go']['main']['App']['DeleteConfig'](arg1);
}

export function GenerateSelfSignedCert() {
  return window['go']['main']['App']['GenerateSelfSignedCert']();
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function Init() {
  return window['go']['main']['App']['Init']();
}

export function ListConfigs() {
  return window['go']['main']['App']['ListConfigs']();
}

export function ParseHopChainString(arg1) {
  return window['go']['main']['App']['ParseHopChainString'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartAll() {
  return window['go']['main']['App']['StartAll']();
}

export function StartTunnel(arg1) {
  return window['go']['main']['App']['StartTunnel'](arg1);
}

export function StopAll() {
  return window['go']['main']['App']['StopAll']();
}

export function StopTunnel(arg1) {
  return window['go']['main']['App']['StopTunnel'](arg1);
}

export function TestTunnelConfig(arg1) {
  return window['go']['main']['App']['TestTunnelConfig'](arg1);
}
